feat: adding view profile Megloblin
jahorwitz/slopopedia pull request #47
Opened 2024-02-16 18:19 UTC by Dbishop15

## Describe your changes
Create a "Me Goblin" tab on the user's profile page to display their wishlist and watched-list, allowing them to view their activity and watchlist.
## Issue ticket number and link

Slop-13:
https://apiary-edtonomy.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-13

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] If there are changes to components, I have added / updated automated tests
- [ ] I have made any necessary updates to Storybook to accompany these changes
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2024-02-18 18:40 UTC, SamPage4427 reviewed
Everything looks good so far. I would just put the code into the tabber folder components since that is where they should be and change the tabber so it looks like the figma.

2024-02-20 00:16 UTC, Dillona25 approved these changes
Everything looks great and the ticket is handled! Though Sam has some comments that I would 2nd here!

2024-02-27 14:20 UTC, jahorwitz commented on src/components/tabber/tabber.jsx
> +export const Tabber = () => {
This component is used in several places and is meant to be re-usable. We should leave it like it was and then create components in the /routes directory that import the tabber components from here and makes the query for the watchlist, sets up the tab list and panels, etc. Same goes for the tab list and panels-- everything in the /components directory needs to remain re-useable or else we will break other parts of the app that are using this component

2024-02-27 14:20 UTC, jahorwitz requested changes
Once you refactor the tabber, drop this ticket back into final-review and I'll take another look! 👍

2024-03-04 15:05 UTC, jahorwitz approved these changes

2024-03-04 15:05 UTC, merged