Feature/slop 18/submitted slops
jahorwitz/slopopedia pull request #58
Opened 2024-03-13 13:25 UTC by jduncan017

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review

- [x ] I have performed a self-review of my code
- [ ] If there are changes to components, I have added / updated automated tests
- [ ] I have made any necessary updates to Storybook to accompany these changes
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings

2024-03-13 22:42 UTC, skwisgaarr8-9 requested changes

2024-03-13 22:42 UTC, skwisgaarr8-9 commented on src/routes/fest-route/fest-sidebar.jsx
> +  const { currentUser } = useContext(CurrentUserContext);
do not get `currentUser` information this way. use our hook `useCurrentUser()`

2024-03-13 22:42 UTC, skwisgaarr8-9 commented on src/routes/submit-route/submitted-slops/submitted-slops-route.jsx
> +  const { currentUser } = useContext(CurrentUserContext);
do not get `currentUser` information this way. use our hook `useCurrentUser()`

2024-03-13 22:52 UTC, skwisgaarr8-9 commented
you also need to remove `export * from "./SubmitList";` from `src/components/index.js` since that file does not exist anymore

2024-03-14 13:46 UTC, mnunezsa95 commented on src/components/index.js
This is throwing an error on my side so I commented it out and it works fine. Not sure if it is needed or if the relative path is just wrong

2024-03-19 20:35 UTC, jduncan017 commented on src/components/index.js
Hey I'm not sure what you're referring to here

2024-03-19 23:30 UTC, jduncan017 commented
Main merged and app tested. All requested changes made. Let me know if there's anything else!

2024-03-20 11:31 UTC, mnunezsa95 commented
> you also need to remove `export * from "./SubmitList";` from `src/components/index.js` since that file does not exist anymore

Resolved

2024-03-21 21:43 UTC, SamPage4427 approved these changes
Everything looks good. Submitted slops show up and the user, if they are an Admin, can approve or deny any of the slop requests. The creator can also update/delete their movie. Slop preview opens when a movie is clicked. Publish and delete send API requests to the backend to change status to either published or delete the movie from the backend. 
Backend is also updated to handle the change in movie status.
Ticket is complete

2024-03-25 22:39 UTC, skwisgaarr8-9 approved these changes

2024-03-26 00:12 UTC, merged