Fix/Slop-31/Combobox Allows For Doubles
jahorwitz/slopopedia pull request #74
Opened 2024-05-01 20:35 UTC by dani9401

## Describe your changes
Before this change, on any given Combobox throughout the application, the user would be able to select the same choice from the dropdown more than once. I updated the way Form.Combobox behaves with the "list" prop it's provided. I also removed some unneeded code that was also partially causing this issue. 

**IMPORTANT NOTE**: I was ONLY able to test this setup on the submit-slop-form. I could not test it on the forms for creating a new fest or the form for a new Blog Post because all of those are currently broken and waiting for approval in other PRs. 

## Issue ticket number and link
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-31 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If there are changes to components, I have added / updated automated tests
- [ ] I have made any necessary updates to Storybook to accompany these changes
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2024-05-02 04:06 UTC, fdlai reviewed
Hi! If you **git pull** while in the main branch, then you can switch to this branch and do **git merge main**, to incorporate the updated changes in main. Then I'm able to test the dropdown boxes in the blogs section. When I do that, it's not working properly, and there are errors in the console. The submit a slop form, seems to work great though!
![2024-05-02_00-01](https://github.com/jahorwitz/slopopedia/assets/112486038/3b5590df-5231-4022-83fb-00171eaea322)

2024-05-03 17:09 UTC, dani9401 commented
Thanks @fdlai! Working on updates now

2024-05-07 17:17 UTC, dani9401 commented
@fdlai and Team - edits have been made and this PR is ready for 2 Peer Reviews :) Thank you!

2024-05-07 19:08 UTC, fdlai reviewed
Hi! The dropdowns for keywords and movies, when working with blog posts, still aren't working for me. In the screenshot, I show that the keywords are cut off (you can see the word 'funny' has been cut off). As far as the movies dropdown, when I try to add a movie, the most I can see is a comma. I'm not really sure what's going on there? 

Are there perhaps changes to the backend that need to be running at the same time as this branch?

![2024-05-07_15-00](https://github.com/jahorwitz/slopopedia/assets/112486038/b3dbc2e5-7eae-4270-8aec-ab3543b89b45)

2024-05-07 19:42 UTC, dani9401 commented
https://github.com/jahorwitz/slopopedia/assets/126746048/9be3a26b-4e3b-47ee-b8de-c474869207bb

2024-05-07 21:07 UTC, bduckdev commented
I just pulled the branch locally and the combobox is working locally for me.  Inputs are not doubled anymore.

2024-05-07 21:44 UTC, fdlai approved these changes
@dani9401 Aah,  you're right! My apologies. I had done **git fetch**, but apparently that doesn't grab your updated changes from the branch. I had to do **git pull** within your branch. Now, the blogs section seems to work. Great job!

2024-05-07 21:47 UTC, dani9401 commented
> I just pulled the branch locally and the combobox is working locally for me. Inputs are not doubled anymore.

@bduckdev Thank you!! When you get a sec can you please marked this as "Approved" so I can push it over into Tomer's queue? :)

2024-05-10 19:18 UTC, dani9401 commented
@bduckdev hey! Would you mind marking this as "approved" so I can get this over into Tomer's queue? Thank you!

2024-05-14 00:32 UTC, marzahlde09 approved these changes
Changes work as described! As for the merge conflict - there was a story I handled where ALL keywords were being attached to new slops. I'm fairly certain your changes will mesh nicely with mine, so we should accept the code from main when merging.

2024-05-14 21:46 UTC, tomershvueli requested changes
The changes to the combo box are looking mostly good. Few things: 
- There's a merge conflict with `main` which you need to resolve before I can merge this in, see screenshot below. 
- I'm seeing a behavior where the combo box now does not populate properly. To repro: 
  - Have a blog post with a keyword tagged to it
  - Hit Edit
  - On the Edit page, on `main` the combo box would have shown the tag in the combo box. On this branch, the combo box is empty when the Edit page loads

![image](https://github.com/jahorwitz/slopopedia/assets/1024355/5a9532e6-c002-47ab-b616-cc0a6699ef19)

2024-05-14 21:46 UTC, tomershvueli commented on src/page/blog/article-page.jsx
> +              //className="relative flex justify-center font-bold font-arial flex-col py-3"
nit: Can remove this if we don't need it

2024-05-15 01:46 UTC, dani9401 commented
@tomershvueli hey there - I have merged from main and handled conflicts. But for some reason my branch is still having issues that main is not having. I thought it was maybe tied to how I handled one of the merge conflicts. So I compared my branch to main, copied over the main code (instead of my code) for those 2 merges I reviewed earlier, and I still can't figure out why my blogs/slops are being submitted without keywords going to the database (and I'm getting map errors in the console for the way to submit functions are handling keywords/slops). Would you possibly be able to point me in the right direction of what I'm missing on this one?

2024-05-15 07:03 UTC, fdlai commented
> @tomershvueli hey there - I have merged from main and handled conflicts. But for some reason my branch is still having issues that main is not having. I thought it was maybe tied to how I handled one of the merge conflicts. So I compared my branch to main, copied over the main code (instead of my code) for those 2 merges I reviewed earlier, and I still can't figure out why my blogs/slops are being submitted without keywords going to the database (and I'm getting map errors in the console for the way to submit functions are handling keywords/slops). Would you possibly be able to point me in the right direction of what I'm missing on this one?

Hey @dani9401 ! I fixed something similar when I worked on my Edit-blog-post PR. I made a video here that might help to give you a direction to go in: https://www.loom.com/share/1dafdd06788a4860a8c002a3b5fff176

2024-05-16 01:33 UTC, dani9401 commented
> > Hey @dani9401 ! I fixed something similar when I worked on my Edit-blog-post PR. I made a video here that might help to give you a direction to go in: https://www.loom.com/share/1dafdd06788a4860a8c002a3b5fff176
> > Oh, and I wouldn't worry about getting the form to correctly submit, when editing. I would say that's more part of that Edit-Blog task.
> 

Hey @fdlai! I played around with this a bit more and made a video follow up for you (link below). Even though the solution isn't entirely in place yet, I went ahead and pushed my commits so you can see my most recent code alongside this video if need be. As you mentioned in your video, my solution for the combobox doubles seems to be impacting your solution for prefilling the edit blog form. I think I'm a bit closer to getting it to work for both of our issues, but not totally there yet. Thanks for working with me on this! 
https://drive.google.com/file/d/1suQb-0LcORRLOd1x7I2oC1UmtWUr8meY/view?usp=sharing

2024-05-16 05:04 UTC, fdlai commented
> > > Hey @dani9401 ! I fixed something similar when I worked on my Edit-blog-post PR. I made a video here that might help to give you a direction to go in: https://www.loom.com/share/1dafdd06788a4860a8c002a3b5fff176
> > > Oh, and I wouldn't worry about getting the form to correctly submit, when editing. I would say that's more part of that Edit-Blog task.
> 
> Hey @fdlai! I played around with this a bit more and made a video follow up for you (link below). Even though the solution isn't entirely in place yet, I went ahead and pushed my commits so you can see my most recent code alongside this video if need be. As you mentioned in your video, my solution for the combobox doubles seems to be impacting your solution for prefilling the edit blog form. I think I'm a bit closer to getting it to work for both of our issues, but not totally there yet. Thanks for working with me on this! https://drive.google.com/file/d/1suQb-0LcORRLOd1x7I2oC1UmtWUr8meY/view?usp=sharing

Hey! I tried coming up with something. I do feel like there's a more elegant solution than what I came up with, but this was the 1st idea that came to my mind. I didn't want to disturb your branch, so I pushed to a separate branch. I also merged main into the branch which is why it might be showing a lot of changes, but really, the only important changes that got it working for me are these:

This green block:
https://github.com/jahorwitz/slopopedia/compare/main...feature/test-solution-for-slop-31#diff-2ceadeddeccacb39d54d89b52d68b672edc5774a4c2baab9dab7d6aff9191558R263

These 2 lines:
https://github.com/jahorwitz/slopopedia/compare/main...feature/test-solution-for-slop-31#diff-2ceadeddeccacb39d54d89b52d68b672edc5774a4c2baab9dab7d6aff9191558R281

And this useEffect:
https://github.com/jahorwitz/slopopedia/compare/main...feature/test-solution-for-slop-31#diff-9a8c83a2a1a1ee92c24a48491121880e45d407aed5635cb6514c58b78f1ac5ecR96

The handleChange function looks a bit rough and messy, and I'm not even sure if using a useState variable is necessary? But if you don't like it, maybe it will give you something to work with, at least.

2024-05-18 13:33 UTC, tomershvueli commented
@dani9401 I'm still able to select duplicate values on the combo-box on the latest code :/

2024-05-18 14:27 UTC, dani9401 commented
> @dani9401 I'm still able to select duplicate values on the combo-box on the latest code :/

Thanks @tomershvueli! Yeah Fred and I are still working on this but I'll ping you when it's ready for another review.

2024-05-20 19:26 UTC, dani9401 commented
@fdlai Hey! Thank you for your feedback! I recorded a video to be more detailed in my response and show you what is happening on my side, BUT essentially your solution solved a ton of our issues, but then a new issue popped up. I spent about an hour trying to work through it but am trying to table how much more time I put into this PR for the sake of Slop 63 getting movement. 

https://drive.google.com/file/d/1u2vpEZQJiVHj8V8_HPjmyze_4oyQdjya/view?usp=sharing

2024-05-20 19:53 UTC, fdlai commented
> @fdlai Hey! Thank you for your feedback! I recorded a video to be more detailed in my response and show you what is happening on my side, BUT essentially your solution solved a ton of our issues, but then a new issue popped up. I spent about an hour trying to work through it but am trying to table how much more time I put into this PR for the sake of Slop 63 getting movement.
> 
> https://drive.google.com/file/d/1u2vpEZQJiVHj8V8_HPjmyze_4oyQdjya/view?usp=sharing

@dani9401 Hey! Just saw your video. I'm familiar with that error, and I believe I have a quick fix for it. That error is seen sometimes because React will complain if the initial value is undefined. As for why **watch(id)** is not undefined in the blog section at the start, but in the slop-form it is, I'd have to inspect things more carefully to explain that. But a quick fix is to just include another 'or' condition, so that if both **selelctedItems** and **watch(id)** are undefined at the start, then we still assign the value to something defined.
![2024-05-20_15-46](https://github.com/jahorwitz/slopopedia/assets/112486038/285d29aa-ba2b-47be-89fc-45bccb3a7381)

2024-05-21 02:26 UTC, dani9401 commented
I think this one is finally ready for you @tomershvueli!

2024-05-21 18:36 UTC, dani9401 commented on src/components/slop-fest-modal.jsx
> +      setValue("invitees", inviteesBefore);
Invitees wasn't prefilling on edit-slop page. So I added this quick fix so I could properly test if the combobox was still allowing doubles.

2024-05-21 18:37 UTC, dani9401 commented on src/components/slop-fest-modal.jsx
> +            list={users}
updated list={} with new 'users' array to fix issue with combobox and prefill

2024-05-21 18:38 UTC, dani9401 commented on src/page/blog/article-page.jsx
> +  const { data: postData } = useQuery(GET_BLOG_POST, {
just updated to 'postData' instead of 'data' as there are a lot of queries in this and it made the code easier to read.

2024-05-21 21:42 UTC, tomershvueli approved these changes
This is working great! See my one note for future reference. Thanks for cleaning up the comments and thanks for sticking with this through the finish line!

2024-05-21 21:42 UTC, merged